# Site settings
title: Curious
email: bansalvipul.111@gmail.com
description: "Personal Blog"
baseurl: ""
url: "http://vipsyvipul.github.io"
twitter_username: vipsy
github_username:  vipsyvipul
port: 8000

# Build settings
markdown: kramdown
permalink: pretty
